# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[('AhkJ64.dll','.'),
    ('AoJia64.dll','.'),
    ('ARegJ64.dll','.'),
    ('AzrJ64.exe','.')],
    datas=[
        ('images\\blyx.ico', 'images'),
        ('images\\cgzm.png', 'images'), 
        ('images\\back.png', 'images'), 
        ('images\\dcr.png', 'images'), 
        ('images\\bx.png', 'images'), 
        ('images\\cs.png', 'images'), 
        ('images\\cs2.png', 'images'), 
        ('images\\jb100.png', 'images'), 
        ('images\\jb100_h.png', 'images'), 
        ('images\\jb90.png', 'images'), 
        ('images\\zhe.png', 'images'), 
        ('images\\ok.png', 'images'), 
        ('images\\zm.png', 'images'), 
        ('images\\zmui1.png', 'images'), 
        ('images\\zmui2.png', 'images'), 
        ('images\\color\\blue.png', 'images\\color'), 
        ('images\\color\\golden.png', 'images\\color'), 
        ('images\\color\\purple.png', 'images\\color'), 
        ('images\\color\\red.png', 'images\\color'), 
        ('images\\color\\white.png', 'images\\color'), 
        ('images\\hero\\aobing.png', 'images\\hero'), 
        ('images\\hero\\baiwuchang.png', 'images\\hero'), 
        ('images\\hero\\heiguafu.png', 'images\\hero'), 
        ('images\\hero\\libai.png', 'images\\hero'), 
        ('images\\hero\\lieren.png', 'images\\hero'), 
        ('images\\hero\\shuangqiang.png', 'images\\hero'), 
        ('images\\hero\\tianshi.png', 'images\\hero'), 
        ('images\\hero\\wangzi.png', 'images\\hero'), 
        ('images\\hero\\wuji.png', 'images\\hero'), 
        ('images\\hero\\tieniangzi.png', 'images\\hero'), 
        ('images\\hero\\deluyi.png', 'images\\hero'), 
        ('images\\hero\\jiushen.png', 'images\\hero'), 
        ('images\\hero\\shengqi.png', 'images\\hero'), 
        ('images\\hero\\kakaxi.png', 'images\\hero')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='x_blyx',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='images\\blyx.ico',
)
